galaxys2-common: disable dexpreopt
For some reasons, build is unable to procees. Build fails while dexpreopt-ing boot image.
Disabling dexpreopt temporarily. As a side note, my build machine (i7-620m) supports sse4.2, thus has no problem in utilizing popcnt feature.

 ERROR: Dex2oat failed to compile a boot image.