galaxys2-common: reconfigure compiler flags
Perhaps the cross-compiler is different, these extensions are unsupported in cm-14.1's prebuilt GCC.
And also, change -Ofast to -O3 because it introduces the following build error:

    error: unknown type name '__extern_always_inline'

According to GCC manual, -Ofast introduces -ffast-math.

Change-Id: I78b9f51e54d8e79393c60af79c99e54ca6833930